# generated by datamodel-codegen:
#   filename:  summarize.yaml
#   timestamp: 2025-09-20T01:44:09+00:00

from __future__ import annotations

from pydantic import BaseModel


class ChatRequest(BaseModel):
    message: str


class ChatResponse(BaseModel):
    reply: str
