# # generated by datamodel-codegen:
# #   filename:  summarize.yaml
# #   timestamp: 2025-09-10T16:08:28+00:00

# from __future__ import annotations
# from pydantic import BaseModel
# from typing import List,Optional


# class HelloRequest(BaseModel):
#     name: str


# class ContactDetails(BaseModel):
#     city: Optional[str]
#     email: Optional[str]
#     mobile: Optional[str]


# class CoverSlide(BaseModel):
#     company_name: Optional[str]
#     logo_description: Optional[str]
#     contact_details: ContactDetails
#     url: Optional[str]
#     tagline: Optional[str]


# class TeamMember(BaseModel):
#     name: Optional[str]
#     role: Optional[str]
#     is_cofounder: bool
#     equity_percent: float
#     justification: Optional[str]


# class ProblemStatement(BaseModel):
#     pain_point: Optional[str]
#     current_alternative: Optional[str]
#     why_better: Optional[str]


# class ProductOverview(BaseModel):
#     description: Optional[str]
#     unique_value: Optional[str]


# class BusinessModel(BaseModel):
#     who_pays: Optional[str]
#     revenue_flow: Optional[str]
#     pricing_summary: Optional[str]


# class MarketSize(BaseModel):
#     region: Optional[str]
#     estimated_customers: int
#     price_point: float
#     potential_revenue: Optional[str]


# class MarketOpportunity(BaseModel):
#     target_customers: Optional[str]
#     market_size: MarketSize
#     future_expansion: Optional[str]


# class Traction(BaseModel):
#     milestones: Optional[str]
#     customers: Optional[str]
#     revenues: Optional[str]
#     visual_proof: Optional[str]


# class CompetitiveLandscape(BaseModel):
#     competitors: Optional[str]
#     differentiation_strategy: Optional[str]


# class YearSummary(BaseModel):
#     revenue: Optional[str]
#     capex: Optional[str]
#     opex: Optional[str]


# class Summary3Years(BaseModel):
#     year1: YearSummary
#     year2: YearSummary
#     year3: YearSummary


# class UnitEconomics(BaseModel):
#     revenue_per_customer: Optional[str]
#     cost_per_customer: Optional[str]


# class Financials(BaseModel):
#     summary_3_years: Summary3Years
#     unit_economics: UnitEconomics


# class FundingNeeds(BaseModel):
#     amount_to_raise: Optional[str]
#     planned_usage: Optional[str]
#     co_investors: Optional[str]
#     runway: Optional[str]
#     milestones_with_funding: Optional[str]
#     follow_on_capital_required: Optional[str]
#     valuation_sought: Optional[str]


# class CapTableEntry(BaseModel):
#     shareholder: Optional[str]
#     equity_percent: Optional[str]


# class PastFunding(BaseModel):
#     year: Optional[str]
#     amount: Optional[str]
#     investors: Optional[str]


# class EquityStructure(BaseModel):
#     cap_table: List[CapTableEntry]
#     founder_investment: Optional[str]
#     past_funding: List[PastFunding]


# class ExitOptions(BaseModel):
#     exit_strategy: Optional[str]
#     examples_in_industry: Optional[str]

# # --- NEW ADDITION: Scorecard ---
# class ScoreCard(BaseModel):
#     team_strength: int        # 1–10
#     market_potential: int     # 1–10
#     product_uniqueness: int   # 1–10
#     traction_progress: int    # 1–10
#     financial_health: int     # 1–10
#     funding_readiness: int    # 1–10
#     overall_score: int        # weighted or avg score


# class StartupPitch(BaseModel):
#     cover_slide: CoverSlide
#     team: List[TeamMember]
#     problem_statement: ProblemStatement
#     product_overview: ProductOverview
#     business_model: BusinessModel
#     market_opportunity: MarketOpportunity
#     traction: Traction
#     competitive_landscape: CompetitiveLandscape
#     financials: Financials
#     funding_needs: FundingNeeds
#     equity_structure: EquityStructure
#     exit_options: ExitOptions
#     score_card: ScoreCard


from __future__ import annotations
from pydantic import BaseModel
from typing import List, Optional, Union


class HelloRequest(BaseModel):
    name: str

# --- Basic Info ---
class BasicInfo(BaseModel):
    id: str
    name: str
    description: Optional[str]
    founded: Optional[str]
    headquarters: Optional[str]
    sector: Optional[str]
    stage: Optional[str]
    employees: Optional[int]
    valuation: Optional[str]
    growth: Optional[float]   # in % percentage
    website: Optional[str]    
    logo: Optional[str]

# --- Financial Metrics ---
class Metrics(BaseModel):
    revenue: Optional[str]
    customers: Optional[str]
    burn: Optional[str]
    runway: Optional[str]
    funding: Optional[str]
    grossMargin: Optional[str]
    cac: Optional[str]
    ltv: Optional[str]
    churnRate: Optional[str]
    nps: Optional[int]
    mrr: Optional[str]
    arr_growth: Optional[str]
    customer_satisfaction: Optional[str] = None
    technology_score: Optional[str] = None
    competitor_avg_satisfaction: Optional[str] = None
    competitor_avg_tech_score: Optional[str] = None
    implementation_speed_advantage: Optional[str] = None
    industry_avg_gross_margin: Optional[str] = None
    competitor_avg_churn: Optional[str] = None
    customer_base_difference: Optional[str] = None
    addressable_market_gap: Optional[str] = None
    underserved_market_share: Optional[str] = None
    top_customer_revenue_concentration: Optional[str] = None
    expected_irr_range: Optional[str] = None
    established_players_market_share: Optional[str] = None
    scale_execution_target: Optional[str] = None
    cost_leadership_advantage: Optional[str] = None
    market_leader_share: Optional[str] = None
    foreign_currency_revenue: Optional[str] = None


class FinancialsTimeSeries(BaseModel):
    labels: List[str]
    revenue: List[float]
    expenses: List[float]
    profit: List[float]
    customers: List[int]

# --- Team ---
class TeamMember(BaseModel):
    id: Optional[str]
    name: Optional[str]
    role: Optional[str]
    background: Optional[str]
    linkedin: Optional[str]
    equity: Optional[float]
    years_experience: Optional[int]

# --- Equity ---
class EquityBreakdownEntry(BaseModel):
    category: str
    percentage: float
    color: Optional[str]

class Equity(BaseModel):
    founders: Optional[float]
    employees: Optional[float]
    investors_previous: Optional[float]
    reserved_future: Optional[float]
    breakdown: List[EquityBreakdownEntry]

# --- Market ---
class Market(BaseModel):
    tam: Optional[str]
    sam: Optional[str]
    som: Optional[str]
    growth_rate: Optional[str]
    market_share: Optional[str]
    target_segment: Optional[str]
    trends: List[str]
    problem_statement: Optional[str]

# --- Product ---
class Product(BaseModel):
    name: Optional[str]
    description: Optional[str]
    features: List[str]
    competitive_advantages: List[str]
    development_stage: Optional[str]


# ----------------
# Risk Factors
# ----------------
class RiskItem(BaseModel):
    title: str
    risk: str
    mitigation: str


class RiskFactors(BaseModel):
    market_saturation: RiskItem
    economic_downturn: RiskItem
    key_person_dependency: RiskItem
    technology_risks: RiskItem

# ----------------
# Exit Strategy
# ----------------
class StrategicAcquirerGroup(BaseModel):
    category: str
    companies: str  # comma-separated in your JSON sample


class MarketMultiples(BaseModel):
    revenue_multiple: str
    growth_premium: str
    recent_comparables: str


class ExitStrategyDetail(BaseModel):
    timeline: Optional[str] = None
    timeline_description: Optional[str] = None
    potential_valuation: Optional[str] = None
    valuation_description: Optional[str] = None
    exit_options: List[str] = []
    strategic_acquirers: List[StrategicAcquirerGroup] = []
    market_multiples: Optional[MarketMultiples] = None



class RevenueType(BaseModel):
    type: str
    description: Optional[str] = None


class PricingTier(BaseModel):
    tier: str
    price: str
    description: Optional[str] = None


class BusinessModel(BaseModel):
    revenue_type: RevenueType
    monetization_strategy: List[str]
    pricing_strategy: List[PricingTier]


# -------------------
# Legal & Compliance
# -------------------
class Incorporation(BaseModel):
    jurisdiction: Optional[str] = None
    entity_type: Optional[str] = None
    incorporation_date: Optional[str] = None


class IntellectualProperty(BaseModel):
    patents_filed: Optional[str] = None
    patent_description: Optional[str] = None
    trademarks: Optional[str] = None


class LegalStructure(BaseModel):
    authorized_shares: Optional[str] = None
    outstanding_shares: Optional[str] = None
    option_pool: Optional[str] = None


class LegalDocumentLC(BaseModel):
    icon: Optional[str] = None
    title: str
    status: Optional[str] = None


class LegalCompliance(BaseModel):
    incorporation: Incorporation
    intellectual_property: IntellectualProperty
    regulatory_compliance: List[str]
    legal_structure: LegalStructure
    key_documents: List[LegalDocumentLC]

# --- Full Deal Data ---
class DealData(BaseModel):
    basicInfo: BasicInfo
    metrics: Metrics
    financials: FinancialsTimeSeries
    team: List[TeamMember]
    equity: Equity
    market: Market
    product: Product
    exit: ExitStrategyDetail
    business: BusinessModel
    legal: LegalCompliance
