# # generated by datamodel-codegen:
# #   filename:  summarize.yaml
# #   timestamp: 2025-09-10T16:08:28+00:00

# from __future__ import annotations
# from pydantic import BaseModel
# from typing import List,Optional


# class HelloRequest(BaseModel):
#     name: str


# class ContactDetails(BaseModel):
#     city: Optional[str]
#     email: Optional[str]
#     mobile: Optional[str]


# class CoverSlide(BaseModel):
#     company_name: Optional[str]
#     logo_description: Optional[str]
#     contact_details: ContactDetails
#     url: Optional[str]
#     tagline: Optional[str]


# class TeamMember(BaseModel):
#     name: Optional[str]
#     role: Optional[str]
#     is_cofounder: bool
#     equity_percent: float
#     justification: Optional[str]


# class ProblemStatement(BaseModel):
#     pain_point: Optional[str]
#     current_alternative: Optional[str]
#     why_better: Optional[str]


# class ProductOverview(BaseModel):
#     description: Optional[str]
#     unique_value: Optional[str]


# class BusinessModel(BaseModel):
#     who_pays: Optional[str]
#     revenue_flow: Optional[str]
#     pricing_summary: Optional[str]


# class MarketSize(BaseModel):
#     region: Optional[str]
#     estimated_customers: int
#     price_point: float
#     potential_revenue: Optional[str]


# class MarketOpportunity(BaseModel):
#     target_customers: Optional[str]
#     market_size: MarketSize
#     future_expansion: Optional[str]


# class Traction(BaseModel):
#     milestones: Optional[str]
#     customers: Optional[str]
#     revenues: Optional[str]
#     visual_proof: Optional[str]


# class CompetitiveLandscape(BaseModel):
#     competitors: Optional[str]
#     differentiation_strategy: Optional[str]


# class YearSummary(BaseModel):
#     revenue: Optional[str]
#     capex: Optional[str]
#     opex: Optional[str]


# class Summary3Years(BaseModel):
#     year1: YearSummary
#     year2: YearSummary
#     year3: YearSummary


# class UnitEconomics(BaseModel):
#     revenue_per_customer: Optional[str]
#     cost_per_customer: Optional[str]


# class Financials(BaseModel):
#     summary_3_years: Summary3Years
#     unit_economics: UnitEconomics


# class FundingNeeds(BaseModel):
#     amount_to_raise: Optional[str]
#     planned_usage: Optional[str]
#     co_investors: Optional[str]
#     runway: Optional[str]
#     milestones_with_funding: Optional[str]
#     follow_on_capital_required: Optional[str]
#     valuation_sought: Optional[str]


# class CapTableEntry(BaseModel):
#     shareholder: Optional[str]
#     equity_percent: Optional[str]


# class PastFunding(BaseModel):
#     year: Optional[str]
#     amount: Optional[str]
#     investors: Optional[str]


# class EquityStructure(BaseModel):
#     cap_table: List[CapTableEntry]
#     founder_investment: Optional[str]
#     past_funding: List[PastFunding]


# class ExitOptions(BaseModel):
#     exit_strategy: Optional[str]
#     examples_in_industry: Optional[str]

# # --- NEW ADDITION: Scorecard ---
# class ScoreCard(BaseModel):
#     team_strength: int        # 1–10
#     market_potential: int     # 1–10
#     product_uniqueness: int   # 1–10
#     traction_progress: int    # 1–10
#     financial_health: int     # 1–10
#     funding_readiness: int    # 1–10
#     overall_score: int        # weighted or avg score


# class StartupPitch(BaseModel):
#     cover_slide: CoverSlide
#     team: List[TeamMember]
#     problem_statement: ProblemStatement
#     product_overview: ProductOverview
#     business_model: BusinessModel
#     market_opportunity: MarketOpportunity
#     traction: Traction
#     competitive_landscape: CompetitiveLandscape
#     financials: Financials
#     funding_needs: FundingNeeds
#     equity_structure: EquityStructure
#     exit_options: ExitOptions
#     score_card: ScoreCard


from __future__ import annotations
from pydantic import BaseModel
from typing import List, Optional, Union


class HelloRequest(BaseModel):
    name: str

# --- Basic Info ---
class BasicInfo(BaseModel):
    id: str
    name: str
    description: Optional[str]
    founded: Optional[str]
    headquarters: Optional[str]
    sector: Optional[str]
    stage: Optional[str]
    employees: Optional[int]
    valuation: Optional[str]
    growth: Optional[str]
    website: Optional[str]
    logo: Optional[str]

# --- Financial Metrics ---
class Metrics(BaseModel):
    revenue: Optional[str]
    customers: Optional[str]
    burn: Optional[str]
    runway: Optional[str]
    funding: Optional[str]
    grossMargin: Optional[str]
    cac: Optional[str]
    ltv: Optional[str]
    churnRate: Optional[str]
    nps: Optional[int]
    mrr: Optional[str]
    arr_growth: Optional[str]

# --- Time series financials ---
class FundingRound(BaseModel):
    year: str
    amount: float
    type: str
    investors: List[str]

class FinancialsTimeSeries(BaseModel):
    labels: List[str]
    revenue: List[float]
    expenses: List[float]
    profit: List[float]
    customers: List[int]
    funding_rounds: List[FundingRound]

# --- Team ---
class TeamMember(BaseModel):
    id: str
    name: str
    role: Optional[str]
    background: Optional[str]
    linkedin: Optional[str]
    equity: Optional[float]
    years_experience: Optional[int]

# --- Equity ---
class EquityBreakdownEntry(BaseModel):
    category: str
    percentage: float
    color: Optional[str]

class Equity(BaseModel):
    founders: Optional[float]
    employees: Optional[float]
    investors_previous: Optional[float]
    reserved_future: Optional[float]
    breakdown: List[EquityBreakdownEntry]

# --- Market ---
class Market(BaseModel):
    tam: Optional[str]
    sam: Optional[str]
    som: Optional[str]
    growth_rate: Optional[str]
    market_share: Optional[str]
    target_segment: Optional[str]
    trends: List[str]
    problem_statement: Optional[str]

# --- Product ---
class Product(BaseModel):
    name: Optional[str]
    description: Optional[str]
    features: List[str]
    competitive_advantages: List[str]
    development_stage: Optional[str]
    technology_stack: List[str]
    integrations: List[str]

# --- Competitors ---
# class Competitor(BaseModel):
#     id: str
#     name: str
#     funding: Optional[str]
#     valuation: Optional[str]
#     customers: Optional[str]
#     growth: Optional[str]
#     market_share: Optional[str]
#     founded: Optional[str]
#     strengths: List[str]
#     weaknesses: List[str]

# --- Risks ---
class RiskEntry(BaseModel):
    type: str
    severity: Optional[str]
    probability: Optional[str]
    description: Optional[str]
    mitigation: Optional[str] = None
    impact: Optional[str] = None

# class Risks(BaseModel):
#     market_risks: List[RiskEntry]
#     operational_risks: List[RiskEntry]
#     financial_risks: List[RiskEntry]

# --- Exit Strategy ---
class PotentialAcquirer(BaseModel):
    name: str
    rationale: Optional[str]
    likelihood: Optional[str]

class ExitStrategy(BaseModel):
    timeline: Optional[str]
    projected_valuation: str  # low/high/base_case
    strategies: List[str]
    potential_acquirers: str  # strategic: List[PotentialAcquirer], financial: List[PotentialAcquirer]
    market_comparables: str  # saas_multiples, growth_premium, expected_irr

# --- Legal ---
class LegalDocument(BaseModel):
    type: str
    status: Optional[str]
    last_updated: Optional[str]

class Legal(BaseModel):
    incorporation: str
    intellectual_property: str
    compliance: str
    legal_structure: str
    key_documents: List[LegalDocument]

# --- Devil's Advocate ---
# class DevilChallenge(BaseModel):
#     claim: str
#     counter_arguments: List[str]

class CriticalRisk(BaseModel):
    factor: str
    description: Optional[str]

# class DevilsAdvocate(BaseModel):
#     growth_challenges: List[DevilChallenge]
#     financial_challenges: List[DevilChallenge]
#     critical_risks: List[CriticalRisk]
#     stress_tests: List[str]

# --- Investment Summary ---
class InvestmentSummary(BaseModel):
    recommendation: Optional[str]
    risk_rating: Optional[str]
    return_potential: Optional[str]
    time_horizon: Optional[str]
    key_highlights: List[str]
    investment_thesis: Optional[str]
    next_steps: List[str]

# --- Full Deal Data ---
class DealData(BaseModel):
    basicInfo: BasicInfo
    metrics: Metrics
    financials: FinancialsTimeSeries
    team: List[TeamMember]
    equity: Equity
    market: Market
    product: Product
    exit: ExitStrategy
    legal: Legal
    investment_summary: InvestmentSummary

