# generated by datamodel-codegen:
#   filename:  summarize.yaml
#   timestamp: 2025-09-10T16:08:28+00:00

from __future__ import annotations

from pydantic import BaseModel


class HelloRequest(BaseModel):
    name: str


class HelloResponse(BaseModel):
    message: str
